# Generated by Django 5.1.4 on 2024-12-25 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('alias', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='PeopleRatingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.people')),
            ],
            options={
                'db_table': 'people_rating_feedback',
            },
        ),
    ]
